# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "a547df8d7eca7e112a5f39cd6b612d5fa2854e8c"

[[deps.GlauberPT]]
deps = ["Random"]
path = "/media/julian/Nuevo vol/UNIVERSIDAD/Investigaci√≥n_Mulet/Parallel_Tempering_Italia/Codigos/MPT_Parallel_Tempering/GlauberPT.jl"
uuid = "cd1fa12f-b0ed-4c0a-9796-002e8e80502a"
version = "1.0.0-DEV"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"
