[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GlauberPT = "cd1fa12f-b0ed-4c0a-9796-002e8e80502a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorTrains = "89893e69-996d-40b1-ba32-8ff5f34c0dd5"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[sources]
GlauberPT = {path = "C:\\Users\\fefif\\Desktop\\PhD\\Note\\Parallel tempering\\GlauberPT.jl"}
